version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  test:
    machine: true
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.12]
    steps:
      - checkout
      - run:
          name: install machine dependencies
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt install python3.9.12
            pip3 install --upgrade pip wheel
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: run tests
          command: python3 manage.py test
workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git
