version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  CI/CD:
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: run tests
          command: python3 manage.py test
      - run:
          name: deploy to heroku
          - heroku/deploy-via-git
workflows:
  heroku_deploy:
    jobs:
      - CI/CD
      # - heroku/deploy-via-git
