version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

executors:


jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python manage.py test
workflows:
  on_commit:
    jobs: 
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
