version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: install machine dependencies
          command: |
            sudo apt-get install python3-pip python3-dev build-essential
            pip3 install --upgrade pip
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: run tests
          command: python3 manage.py test
workflows:
  on_commit:
    jobs: 
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
