version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
        name: install machine dependencies
        command: |
          sudo apt-get install python3-pip python3-dev build-essential
          pip install --upgrade pip
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python manage.py test
workflows:
  on_commit:
    jobs: 
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
